### ISSUE TITLE
Return error message from API when key already exists in database for create activity

### ISSUE THREAD

**Issue by nweiskirch** [nweiskirch/7301_junior_design_project#105]
14:40:55 web.1   |  IntegrityError: duplicate key value violates unique constraint "tb_activity_title_key"
14:40:55 web.1   |  DETAIL:  Key (title)=(nate) already exists.
14:40:55 web.1   |  CONTEXT:  SQL statement "INSERT INTO tb_activity
14:40:55 web.1   |          (
14:40:55 web.1   |              title,
14:40:55 web.1   |              instructions,
14:40:55 web.1   |              activity_type
14:40:55 web.1   |          )
14:40:55 web.1   |          VALUES
14:40:55 web.1   |          (
14:40:55 web.1   |              my_title,
14:40:55 web.1   |              my_instructions,
14:40:55 web.1   |              my_activity_type
14:40:55 web.1   |          )
14:40:55 web.1   |          RETURNING activity"
14:40:55 web.1   |  PL/pgSQL function fn_create_activity(character varying,character varying,character varying,json) line 18 at SQL statement

We want to let the user know when this happens

**Comment by ryanvoor** [comment]
api will return -1 if the created activity didnt work. Only user relevant reason should be that it was a duplicate

**Comment by ryanvoor** [comment]
javascript needs to be adjusted to handle that response from the api
