### ISSUE TITLE
Teacher-Student assignements

### ISSUE THREAD

**Issue by nweiskirch** [nweiskirch/7301_junior_design_project#88]
Add ability to assign a teacher to a student via API and in database and recall those assignments with either Student ID or Teacher ID
Assignment should have
    - Teacher ID
    - Student ID
    - Type (Primary, Secondary, Temporary)

**Comment by ryanvoor** [comment]
I believe the only part of this issue that hasn't been completed is the Type of student/teacher assignments. We need to discuss whether we actually want this functionality before this issue can continue to be worked on.

**Comment by ryanvoor** [comment]
decided that the additional types for these assignments was not necessary
